<#
.SYNOPSIS
    First-run configuration for a freshly installed Mirror Mind.

.DESCRIPTION
    Writes the .env file, initializes the user's identity home, and (optionally)
    validates the OpenRouter API key with a friendly message on failure.

    Values are normally collected by the Inno Setup wizard and passed as
    parameters. When run interactively without parameters it prompts.

.PARAMETER InstallDir
    Directory containing the Mirror clone (where .env must live).

.PARAMETER MirrorUser
    Value for MIRROR_USER (resolves the user's identity home).

.PARAMETER OpenRouterApiKey
    OpenRouter API key (embeddings, memory extraction, /mm-consult).

.PARAMETER SkipValidation
    Do not perform the live OpenRouter connectivity check.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$InstallDir,
    [string]$MirrorUser,
    [string]$OpenRouterApiKey,
    [switch]$SkipValidation
)

Set-StrictMode -Version Latest
# PS 5.1: 'Continue' so native commands (uv run ...) writing to stderr do not
# raise spurious terminating errors; failures are detected via $LASTEXITCODE and
# explicit throws, and hard-failing cmdlets get -ErrorAction Stop.
$ErrorActionPreference = 'Continue'

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
Import-Module (Join-Path $here 'lib\MirrorInstall.psm1') -Force

# This phase runs in its own process (launched after bootstrap), so refresh PATH
# to pick up tools installed moments ago - notably uv, needed by 'memory init'.
Update-SessionPath

function Read-NonEmpty {
    param([string]$Prompt, [switch]$Secret)
    while ($true) {
        if ($Secret) {
            $secure = Read-Host -Prompt $Prompt -AsSecureString
            $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
            $value = [Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr)
            [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
        } else {
            $value = Read-Host -Prompt $Prompt
        }
        if ($value -and $value.Trim()) { return $value.Trim() }
        Write-Host '  (a value is required)' -ForegroundColor Yellow
    }
}

function Write-EnvFile {
    param([string]$Dir, [string]$User, [string]$ApiKey)
    $envPath = Join-Path $Dir '.env'
    $content = @(
        "# Generated by the Mirror Mind Windows installer",
        "MIRROR_USER=$User",
        "OPENROUTER_API_KEY=$ApiKey",
        "PYTHONUTF8=1"
    ) -join "`n"
    # Write UTF-8 without BOM so the Python dotenv/config reader stays happy.
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($envPath, $content + "`n", $utf8NoBom)
    Write-MirrorLog -Message "wrote .env for user '$User' at $envPath" | Out-Null
    return $envPath
}

function Initialize-Identity {
    param([string]$Dir, [string]$User)
    Invoke-MirrorStep -Name 'initialize identity' -Action {
        Push-Location $Dir
        try {
            & uv run python -m memory init $User
            if ($LASTEXITCODE -ne 0) { throw "memory init failed ($LASTEXITCODE)" }
        } finally { Pop-Location }
    } -OnErrorFriendly {
        param($ex)
        New-FriendlyError -Code 'INIT_FAILED' `
            -Message 'Could not initialize your Mirror identity.' `
            -Cause $ex.Exception.Message `
            -Action 'Re-run the installer. If it persists, share the log file.'
    }
}

function Test-OpenRouter {
    param([string]$ApiKey)
    if ($SkipValidation) { return }
    Invoke-MirrorStep -Name 'validate OpenRouter key' -Action {
        try {
            $resp = Invoke-WebRequest -Uri 'https://openrouter.ai/api/v1/key' `
                -Headers @{ Authorization = "Bearer $ApiKey" } `
                -UseBasicParsing -TimeoutSec 20 -ErrorAction Stop
            if ($resp.StatusCode -ne 200) { throw "unexpected status $($resp.StatusCode)" }
        } catch {
            throw 'OpenRouter did not accept the API key.'
        }
    } -OnErrorFriendly {
        param($ex)
        New-FriendlyError -Code 'OPENROUTER_INVALID' `
            -Message 'Your OpenRouter API key could not be verified.' `
            -Cause 'The key may be wrong, revoked, or the account has no credits.' `
            -Action 'Check the key at https://openrouter.ai/keys and add at least $5 in credits, then re-run configuration.'
    }
}

try {
    Write-Host ''
    Write-Host 'Mirror Mind - first-run configuration' -ForegroundColor White
    Write-Host '-------------------------------------'

    if (-not $MirrorUser) { $MirrorUser = Read-NonEmpty -Prompt 'Your name (MIRROR_USER)' }
    if (-not $OpenRouterApiKey) { $OpenRouterApiKey = Read-NonEmpty -Prompt 'OpenRouter API key' -Secret }

    Test-OpenRouter -ApiKey $OpenRouterApiKey
    $envPath = Write-EnvFile -Dir $InstallDir -User $MirrorUser -ApiKey $OpenRouterApiKey
    Write-Host ("  [ok]      wrote {0}" -f $envPath)
    Initialize-Identity -Dir $InstallDir -User $MirrorUser
    Write-Host ("  [ok]      identity initialized for '{0}'" -f $MirrorUser)
    Write-Host ''
    Write-Host 'Configuration complete.' -ForegroundColor Green
    exit 0
} catch {
    $obj = $_.TargetObject
    if ($obj -and ($obj.PSObject.Properties.Name -contains 'IsFriendly') -and $obj.IsFriendly) {
        Write-Host (Format-FriendlyError $obj.Friendly) -ForegroundColor Red
    } else {
        $fe = New-FriendlyError -Code 'CONFIG_UNEXPECTED' -Message 'Configuration hit an unexpected problem.' `
            -Cause $_.Exception.Message -Action 'Re-run configuration. If it persists, share the log file.'
        Write-Host (Format-FriendlyError $fe) -ForegroundColor Red
    }
    exit 1
}
